export enum BusinessCode {
  // Generic / System
  SUCCESS = 'SYS_000',
  INTERNAL_ERROR = 'SYS_INT',

  // MongoDB
  INVALID_MONGODB_ID = 'MDB_100',

  // User Module
  USER_SUCCESS = 'USR_000',
  USER_CREATED = 'USR_001',
  USER_UPDATED = 'USR_002',
  USER_DELETED = 'USR_003',
  USER_NOT_FOUND = 'USR_100',
  DUPLICATE_USERNAME = 'USR_101',
  DUPLICATE_EMAIL = 'USR_102',

  // Permission Module
  PERMISSION_SUCCESS = 'PER_000',
  PERMISSION_CREATED = 'PER_001',
  PERMISSION_UPDATED = 'PER_002',
  PERMISSION_DELETED = 'PER_003',
  PERMISSION_EXIST = 'PER_100',
  PERMISSION_NOT_FOUND = 'PER_101',
  PERMISSION_UPDATED_FAIL = 'PER_102',
  PERMISSION_DELETED_FAIL = 'PER_103',

  PERMISSION_GET_ALL_SUCCESS = 'PER_200',

  // Validation / Input
  NO_FIELD_UPDATED = 'VAL_001',
  INVALID_FIELD = 'VAL_002',
  VALIDATION_FAILED = 'VAL_100',

}