// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/auth/google-success": {
    params: {};
  };
  "/auth/google-failure": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/roles": {
    params: {};
  };
  "/permissions": {
    params: {};
  };
  "/casts": {
    params: {};
  };
  "/genres": {
    params: {};
  };
  "/movies": {
    params: {};
  };
  "/videos": {
    params: {};
  };
  "/account/:id": {
    params: {
      "id": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/auth/google-success" | "/auth/google-failure" | "/register" | "/dashboard" | "/users" | "/roles" | "/permissions" | "/casts" | "/genres" | "/movies" | "/videos" | "/account/:id" | "/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/guards/guestGuard.tsx": {
    id: "routes/guards/guestGuard";
    page: "/login" | "/auth/google-success" | "/auth/google-failure" | "/register";
  };
  "layouts/authLayout.tsx": {
    id: "layouts/authLayout";
    page: "/login" | "/auth/google-success" | "/auth/google-failure" | "/register";
  };
  "routes/auth/login.tsx": {
    id: "routes/auth/login";
    page: "/login";
  };
  "routes/auth/googleCallback.tsx": {
    id: "routes/auth/googleCallback";
    page: "/auth/google-success";
  };
  "routes/auth/googleError.tsx": {
    id: "routes/auth/googleError";
    page: "/auth/google-failure";
  };
  "routes/auth/register.tsx": {
    id: "routes/auth/register";
    page: "/register";
  };
  "routes/guards/authGuard.tsx": {
    id: "routes/guards/authGuard";
    page: "/dashboard" | "/users" | "/roles" | "/permissions" | "/casts" | "/genres" | "/movies" | "/videos" | "/account/:id";
  };
  "layouts/adminLayout.tsx": {
    id: "layouts/adminLayout";
    page: "/dashboard" | "/users" | "/roles" | "/permissions" | "/casts" | "/genres" | "/movies" | "/videos";
  };
  "routes/dashboard/overview.tsx": {
    id: "routes/dashboard/overview";
    page: "/dashboard";
  };
  "routes/dashboard/users/userPage.tsx": {
    id: "routes/dashboard/users/userPage";
    page: "/users";
  };
  "routes/dashboard/roles/rolePage.tsx": {
    id: "routes/dashboard/roles/rolePage";
    page: "/roles";
  };
  "routes/dashboard/permissions/permissionPage.tsx": {
    id: "routes/dashboard/permissions/permissionPage";
    page: "/permissions";
  };
  "routes/dashboard/casts/castPage.tsx": {
    id: "routes/dashboard/casts/castPage";
    page: "/casts";
  };
  "routes/dashboard/genres/genrePage.tsx": {
    id: "routes/dashboard/genres/genrePage";
    page: "/genres";
  };
  "routes/dashboard/movies/movieList.tsx": {
    id: "routes/dashboard/movies/movieList";
    page: "/movies";
  };
  "routes/dashboard/videos/videoPage.tsx": {
    id: "routes/dashboard/videos/videoPage";
    page: "/videos";
  };
  "routes/account/accountInfo.tsx": {
    id: "routes/account/accountInfo";
    page: "/account/:id";
  };
  "routes/notFound.tsx": {
    id: "routes/notFound";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/guards/guestGuard": typeof import("./app/routes/guards/guestGuard.tsx");
  "layouts/authLayout": typeof import("./app/layouts/authLayout.tsx");
  "routes/auth/login": typeof import("./app/routes/auth/login.tsx");
  "routes/auth/googleCallback": typeof import("./app/routes/auth/googleCallback.tsx");
  "routes/auth/googleError": typeof import("./app/routes/auth/googleError.tsx");
  "routes/auth/register": typeof import("./app/routes/auth/register.tsx");
  "routes/guards/authGuard": typeof import("./app/routes/guards/authGuard.tsx");
  "layouts/adminLayout": typeof import("./app/layouts/adminLayout.tsx");
  "routes/dashboard/overview": typeof import("./app/routes/dashboard/overview.tsx");
  "routes/dashboard/users/userPage": typeof import("./app/routes/dashboard/users/userPage.tsx");
  "routes/dashboard/roles/rolePage": typeof import("./app/routes/dashboard/roles/rolePage.tsx");
  "routes/dashboard/permissions/permissionPage": typeof import("./app/routes/dashboard/permissions/permissionPage.tsx");
  "routes/dashboard/casts/castPage": typeof import("./app/routes/dashboard/casts/castPage.tsx");
  "routes/dashboard/genres/genrePage": typeof import("./app/routes/dashboard/genres/genrePage.tsx");
  "routes/dashboard/movies/movieList": typeof import("./app/routes/dashboard/movies/movieList.tsx");
  "routes/dashboard/videos/videoPage": typeof import("./app/routes/dashboard/videos/videoPage.tsx");
  "routes/account/accountInfo": typeof import("./app/routes/account/accountInfo.tsx");
  "routes/notFound": typeof import("./app/routes/notFound.tsx");
};